<?php  //[STAMP] 04dae0fbdecc90de448e7c9364169dee
// phpcs:ignoreFile
namespace justinholtweb\peek\tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
